theme: jekyll-theme-hacker

# default: kramdown
markdown: GFM

title: Golden Codes - armanexplorer planet
description: You will find practical code snippets of Git, Django, Python and others here

collections:

  git:
    output: true
    permalink: /:collection/:name

  django:
    output: true
    permalink: /:collection/:name

  python:
    output: true
    permalink: /:collection/:name

  typescript:
    output: true
    permalink: /:collection/:name